name: Fit App Prod Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}} docker.io
      - name: Build Docker Image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/fitapp .
      - name: Push Image Docker
        run: docker push ${{secrets.DOCKER_USERNAME}}/fitapp

#  deploy:
#    needs: build
#    runs-on: self-hosted
#    steps:
#      - name: Pull image from dockerhub
#        run: docker pull ${{secrets.DOCKER_USERNAME}}/fitapp
#      - name: Remove previous docker container
#        run: docker rm -f fitapp_prod
#      - name: Run docker container
#        run : docker run -d -p 8285:8285  -e DB_NAME=${{secrets.DB_NAME}}  -e DB_CONNECTION_USER_NAME=${{secrets.DB_CONNECTION_USER_NAME}}  -e DB_CONNECTION_PASSWORD='${{secrets.DB_CONNECTION_PASSWORD}}'  -e RUN_FLYWAY=${{secrets.RUN_FLYWAY}}  -e DB_CONNECTION_HOST='${{secrets.DB_CONNECTION_HOST}}' --restart=always --name fitapp_prod dakkee/fitapp

